cask_args appdir: "/Applications"

brew "tree"
brew "go"
brew "gh"
brew "protobuf"
brew "grpcurl"
brew "colordiff"
brew "nvm"
brew "awscli"
brew "aws-vault"
brew "bufbuild/buf/buf"
brew "goose"
brew "hashicorp/tap/terraform"
brew "libpq"
brew "mysql-client"
brew "cocoapods"
brew "ffmpeg"
brew "golangci-lint"

cask "slack"
cask "google-chrome"
cask "visual-studio-code"
cask "zoom"
cask "warp"
cask "docker"
cask "discord"
cask "brave-browser"

mas "LINE", id: 539883307
mas "Bitwarden", id: 1352778147
