"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$character"""

right_format = """$cmd_duration"""

add_newline = false

[directory]
style = "bold #89b4fa"
truncation_length = 3
truncate_to_repo = true

[character]
success_symbol = "[❯](bold #a6e3a1)"
error_symbol = "[❯](bold #f38ba8)"

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold #cba6f7"

[git_status]
format = "([$all_status$ahead_behind]($style)) "
style = "bold #fab387"

[cmd_duration]
format = "[$duration]($style)"
style = "dimmed #f9e2af"
min_time = 2000
